# CMake generated Testfile for 
# Source directory: /home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch
# Build directory: /home/jarvis/Documents/ns-allinone-3.42/ns-3.42/cmake-cache/scratch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-scratch_chat1 "ns3.42-chat1-default")
set_tests_properties(ctest-scratch_chat1 PROPERTIES  WORKING_DIRECTORY "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_cttc-nr-demo "ns3.42-cttc-nr-demo-default")
set_tests_properties(ctest-scratch_cttc-nr-demo PROPERTIES  WORKING_DIRECTORY "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_demo "ns3.42-demo-default")
set_tests_properties(ctest-scratch_demo PROPERTIES  WORKING_DIRECTORY "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_scratch-simulator "ns3.42-scratch-simulator-default")
set_tests_properties(ctest-scratch_scratch-simulator PROPERTIES  WORKING_DIRECTORY "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_scratch "ns3.42-scratch-default")
set_tests_properties(ctest-scratch_scratch PROPERTIES  WORKING_DIRECTORY "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_scratch_prev "ns3.42-scratch_prev-default")
set_tests_properties(ctest-scratch_scratch_prev PROPERTIES  WORKING_DIRECTORY "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_scratchraw "ns3.42-scratchraw-default")
set_tests_properties(ctest-scratch_scratchraw PROPERTIES  WORKING_DIRECTORY "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_subdir_scratch-subdir "ns3.42-scratch-subdir-default")
set_tests_properties(ctest-scratch_subdir_scratch-subdir PROPERTIES  WORKING_DIRECTORY "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build/scratch/subdir/" _BACKTRACE_TRIPLES "/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;109;create_scratch;/home/jarvis/Documents/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
subdirs("nested-subdir")
